// <auto-generated />
namespace web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RemoverCategoriaCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoverCategoriaCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201909272232041_RemoverCategoriaCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
